# Copyright (c) Tailscale Inc & AUTHORS
# SPDX-License-Identifier: BSD-3-Clause

# The ServiceAccount that ProxyGroups of type "api-server" will use.
# Does not need any special permissions unless auth is enabled.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-server-proxy
  namespace: {{ .Release.Namespace }}
---
# If deprecated setting used, enable both legacy and new workflows.
# If new setting used, enable only new workflow.
{{ if or (eq .Values.apiServerProxyConfig.mode "true")
  (eq .Values.apiServerProxyConfig.authEnabled "true") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tailscale-auth-proxy
rules:
- apiGroups: [""]
  resources: ["users", "groups"]
  verbs: ["impersonate"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tailscale-auth-proxy
subjects:
{{- if eq .Values.apiServerProxyConfig.mode "true" }}
- kind: ServiceAccount
  name: operator
  namespace: {{ .Release.Namespace }}
{{- end }}
- kind: ServiceAccount
  name: api-server-proxy
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: tailscale-auth-proxy
  apiGroup: rbac.authorization.k8s.io
{{ end }}
