# Copyright (c) Tailscale Inc & AUTHORS
# SPDX-License-Identifier: BSD-3-Clause

{{ if and .Values.oauth .Values.oauth.clientId .Values.oauth.clientSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
  namespace: {{ .Release.Namespace }}
stringData:
  client_id: {{ .Values.oauth.clientId }}
  client_secret: {{ .Values.oauth.clientSecret }}
{{- end -}}
