// Copyright (c) Tailscale Inc & contributors
// SPDX-License-Identifier: BSD-3-Clause

package tsnet2

import (
	"context"
	"errors"
	"net"
	"net/netip"

	"github.com/tailscale/wireguard-go/tun"
	"tailscale.com/ipn"
	"tailscale.com/ipn/ipnstate"
	"tailscale.com/types/logger"
)

// errNotImplemented is the sentinel returned by every Server method while the
// daemon-side implementation is being built out. It allows the integration
// test to detect "this is still RED" without needing to string-match.
var errNotImplemented = errors.New("tsnet2: not implemented")

// ErrNotImplemented is returned from methods on Server that have not yet been
// implemented. Callers can use [errors.Is] to detect this case.
var ErrNotImplemented = errNotImplemented

// Server is an embedded Tailscale node that proxies all of its
// network and control-plane state through an out-of-process daemon
// (tsnet2d) over a Unix socket.
//
// The public API is intended to match [tailscale.com/tsnet.Server] so
// programs can switch implementations by changing a single import line.
//
// Exported fields may be changed until the first method call.
type Server struct {
	// Dir specifies the name of the directory to use for state. If empty,
	// a directory is selected automatically under [os.UserConfigDir] based
	// on the name of the binary.
	//
	// In tsnet2, the daemon owns most of the persistent state. Dir is
	// still used for any in-app artifacts (for example, the per-Server
	// log file).
	Dir string

	// Store specifies the state store to use.
	//
	// In tsnet2 the daemon owns the canonical state store. This field
	// is retained for API compatibility with tsnet but is currently
	// only used if the daemon delegates persistence back to the app.
	Store ipn.StateStore

	// Hostname is the hostname to present to the control server.
	// If empty, the binary name is used.
	Hostname string

	// UserLogf, if non-nil, specifies the logger to use for logs
	// generated by the Server itself intended to be seen by the user,
	// such as the AuthURL for login and status updates. If unset,
	// [log.Printf] is used.
	UserLogf logger.Logf

	// Logf, if set, is used for logs generated by the backend such as
	// the LocalBackend and MagicSock (forwarded from the daemon). It is
	// verbose and intended for debugging. If unset, logs are discarded.
	Logf logger.Logf

	// Ephemeral, if true, specifies that the instance should register
	// as an Ephemeral node.
	Ephemeral bool

	// AuthKey, if non-empty, is the auth key to create the node and
	// will be preferred over the TS_AUTHKEY environment variable. If
	// the node is already created (from state previously stored in
	// Store), then this field is not used.
	AuthKey string

	// ControlURL optionally specifies the coordination server URL.
	// If empty, the daemon's default or the TS_CONTROL_URL
	// environment variable is used.
	ControlURL string

	// Port is the UDP port the daemon listens on for WireGuard and
	// peer-to-peer traffic. If zero, a port is automatically selected
	// by the daemon. Leave this field at zero unless you know what
	// you are doing.
	Port uint16

	// Tun, if non-nil, specifies a custom tun.Device. In tsnet2 the TUN
	// must live in the daemon process, not the app. This field is
	// retained for API compatibility but is currently expected to be
	// nil; non-nil values are rejected by Start.
	Tun tun.Device

	// AdvertiseTags specifies tags that should be applied to this node,
	// for purposes of ACL enforcement.
	AdvertiseTags []string

	// SocketPath is the filesystem path of the Unix socket exposed by
	// the tsnet2d daemon that this Server should connect to.
	//
	// If empty, Start will fail with an error: tsnet2 does not
	// auto-spawn a daemon — the user is expected to launch tsnet2d
	// out of band (e.g., as a systemd unit).
	SocketPath string

	// TrafficLogPath, if non-empty, is an override for the path the
	// daemon should write its JSON Lines traffic log to. If empty,
	// the daemon uses its own default location inside its state dir.
	//
	// This field is informational only on the app side; the daemon
	// decides whether to honor it.
	TrafficLogPath string
}

// FallbackTCPHandler describes the callback which conditionally handles an
// incoming TCP flow for the provided (src, dst) address pairs. These are
// registered as handlers of last resort and are called only if no
// registered listener could handle the incoming flow.
//
// If the callback returns intercept=false, the flow is rejected.
//
// When intercept=true, the behavior depends on whether the returned handler
// is non-nil: if nil, the connection is rejected. If non-nil, handler takes
// over the TCP conn.
type FallbackTCPHandler func(src, dst netip.AddrPort) (handler func(net.Conn), intercept bool)

// Start connects the server to the tailnet via the tsnet2d daemon.
// Optional: any calls to Dial/Listen will also call Start.
func (s *Server) Start() error {
	return errNotImplemented
}

// Up connects the server to the tailnet and waits until it is running.
// On success it returns the current status, including a Tailscale IP address.
func (s *Server) Up(ctx context.Context) (*ipnstate.Status, error) {
	return nil, errNotImplemented
}

// Close stops the server.
//
// It must not be called before or concurrently with Start.
func (s *Server) Close() error {
	return errNotImplemented
}

// Listen announces only on the Tailscale network.
// It will start the server if it has not been started yet.
func (s *Server) Listen(network, addr string) (net.Listener, error) {
	return nil, errNotImplemented
}

// ListenTLS announces only on the Tailscale network.
// It returns a TLS listener wrapping the tsnet2 listener.
// It will start the server if it has not been started yet.
func (s *Server) ListenTLS(network, addr string) (net.Listener, error) {
	return nil, errNotImplemented
}

// Dial connects to the address on the tailnet.
// It will start the server if it has not been started yet.
func (s *Server) Dial(ctx context.Context, network, address string) (net.Conn, error) {
	return nil, errNotImplemented
}

// TailscaleIPs returns IPv4 and IPv6 addresses for this node. If the
// node has not yet joined a tailnet or is otherwise unaware of its own
// IP addresses, the returned ip4, ip6 will be !netip.IsValid().
func (s *Server) TailscaleIPs() (ip4, ip6 netip.Addr) {
	return netip.Addr{}, netip.Addr{}
}

// GetRootPath returns the root path of the tsnet2 server (i.e., the
// in-application state directory).
func (s *Server) GetRootPath() string {
	return s.Dir
}

// RegisterFallbackTCPHandler registers a callback which will be called
// to handle a TCP flow to this tsnet2 node for which no listeners
// will handle.
//
// If multiple fallback handlers are registered, they will be called in an
// undefined order. The returned function can be used to deregister this
// callback.
func (s *Server) RegisterFallbackTCPHandler(cb FallbackTCPHandler) func() {
	return func() {}
}

// CertDomains returns the list of domains for which the server can
// provide TLS certificates. These are also the DNS names for the Server.
// If the server is not running, it returns nil.
func (s *Server) CertDomains() []string {
	return nil
}
