// Copyright (c) 2021 Tailscale Inc & AUTHORS All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by the following command; DO NOT EDIT.
//   tailscale.com/cmd/viewer -type Match

package filter

import (
	"inet.af/netaddr"
	"tailscale.com/types/ipproto"
)

// View makes a readonly view of Match.
func (src *Match) View() MatchView {
	return MatchView{src}
}

// MatchView is a readonly view of Match.
type MatchView struct{ ж *Match }

func (v MatchView) Valid() bool              { return v.ж != nil }
func (v MatchView) IPProto() []ipproto.Proto { return v.ж.IPProto }
func (v MatchView) Dsts() []NetPortRange     { return v.ж.Dsts }
func (v MatchView) Srcs() []netaddr.IPPrefix { return v.ж.Srcs }

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _MatchViewNeedsRegeneration = Match(struct {
	IPProto []ipproto.Proto
	Dsts    []NetPortRange
	Srcs    []netaddr.IPPrefix
}{})
