// Copyright (c) 2020 Tailscale Inc & AUTHORS All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by tailscale.com/cmd/cloner -type Match; DO NOT EDIT.

package filter

import (
	"inet.af/netaddr"
)

// Clone makes a deep copy of Match.
// The result aliases no memory with the original.
func (src *Match) Clone() *Match {
	if src == nil {
		return nil
	}
	dst := new(Match)
	*dst = *src
	dst.Dsts = append(src.Dsts[:0:0], src.Dsts...)
	dst.Srcs = append(src.Srcs[:0:0], src.Srcs...)
	return dst
}

// A compilation failure here means this code must be regenerated, with command:
//   tailscale.com/cmd/cloner -type Match
var _MatchNeedsRegeneration = Match(struct {
	Dsts []NetPortRange
	Srcs []netaddr.IPPrefix
}{})
