// Copyright (c) Tailscale Inc & contributors
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by gen.go; DO NOT EDIT.

//go:build !ts_omit_dnsresolvecache

package buildfeatures

// HasDNSResolveCache is whether the binary was built with support for modular feature "Persist successful DNS resolutions to disk for use on later boots with broken DNS".
// Specifically, it's whether the binary was NOT built with the "ts_omit_dnsresolvecache" build tag.
// It's a const so it can be used for dead code elimination.
const HasDNSResolveCache = true
