// Copyright (c) Tailscale Inc & contributors
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by gen.go; DO NOT EDIT.

//go:build !ts_omit_flashappliance

package buildfeatures

// HasFlashAppliance is whether the binary was built with support for modular feature "'tailscale configure flash-appliance' CLI command for writing a Tailscale appliance image to a local disk".
// Specifically, it's whether the binary was NOT built with the "ts_omit_flashappliance" build tag.
// It's a const so it can be used for dead code elimination.
const HasFlashAppliance = true
