// Copyright (c) Tailscale Inc & contributors
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by gen.go; DO NOT EDIT.

//go:build !ts_omit_tunlinkstats

package buildfeatures

// HasTUNLinkStats is whether the binary was built with support for modular feature "Poll extended TUN link statistics (Linux only)".
// Specifically, it's whether the binary was NOT built with the "ts_omit_tunlinkstats" build tag.
// It's a const so it can be used for dead code elimination.
const HasTUNLinkStats = true
