// Copyright (c) Tailscale Inc & AUTHORS
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by gen.go; DO NOT EDIT.

//go:build ts_omit_oauthkey

package buildfeatures

// HasOAuthKey is whether the binary was built with support for modular feature "OAuth secret-to-authkey resolution support".
// Specifically, it's whether the binary was NOT built with the "ts_omit_oauthkey" build tag.
// It's a const so it can be used for dead code elimination.
const HasOAuthKey = false
