// Copyright (c) Tailscale Inc & AUTHORS
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by gen.go; DO NOT EDIT.

//go:build ts_omit_clientmetrics

package buildfeatures

// HasClientMetrics is whether the binary was built with support for modular feature "Client metrics support".
// Specifically, it's whether the binary was NOT built with the "ts_omit_clientmetrics" build tag.
// It's a const so it can be used for dead code elimination.
const HasClientMetrics = false
