// Copyright (c) Tailscale Inc & AUTHORS
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by gen.go; DO NOT EDIT.

//go:build !ts_omit_cliconndiag

package buildfeatures

// HasCLIConnDiag is whether the binary was built with support for modular feature "CLI connection error diagnostics".
// Specifically, it's whether the binary was NOT built with the "ts_omit_cliconndiag" build tag.
// It's a const so it can be used for dead code elimination.
const HasCLIConnDiag = true
