// Copyright (c) Tailscale Inc & AUTHORS
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by gen.go; DO NOT EDIT.

//go:build ts_omit_ssh

package buildfeatures

// HasSSH is whether the binary was built with support for modular feature "Tailscale SSH support".
// Specifically, it's whether the binary was NOT built with the "ts_omit_ssh" build tag.
// It's a const so it can be used for dead code elimination.
const HasSSH = false
