// Copyright (c) Tailscale Inc & contributors
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by gen.go; DO NOT EDIT.

//go:build ts_omit_colorable

package buildfeatures

// HasColorable is whether the binary was built with support for modular feature "Colorized terminal output".
// Specifically, it's whether the binary was NOT built with the "ts_omit_colorable" build tag.
// It's a const so it can be used for dead code elimination.
const HasColorable = false
