// Copyright (c) Tailscale Inc & contributors
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by gen.go; DO NOT EDIT.

//go:build !ts_omit_nattraversal

package buildfeatures

// HasNATTraversal is whether the binary was built with support for modular feature "NAT traversal: STUN, disco hole punching, and UDP peer relay client support (if omitted, direct UDP works only to peers with directly reachable endpoints)".
// Specifically, it's whether the binary was NOT built with the "ts_omit_nattraversal" build tag.
// It's a const so it can be used for dead code elimination.
const HasNATTraversal = true
