// Copyright (c) Tailscale Inc & AUTHORS
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by gen.go; DO NOT EDIT.

//go:build ts_omit_kube

package buildfeatures

// HasKube is whether the binary was built with support for modular feature "Kubernetes integration".
// Specifically, it's whether the binary was NOT built with the "ts_omit_kube" build tag.
// It's a const so it can be used for dead code elimination.
const HasKube = false
