// Copyright (c) Tailscale Inc & AUTHORS
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by gen.go; DO NOT EDIT.

//go:build !ts_omit_outboundproxy

package buildfeatures

// HasOutboundProxy is whether the binary was built with support for modular feature "Support running an outbound localhost HTTP/SOCK5 proxy support that sends traffic over Tailscale".
// Specifically, it's whether the binary was NOT built with the "ts_omit_outboundproxy" build tag.
// It's a const so it can be used for dead code elimination.
const HasOutboundProxy = true
