// Copyright (c) Tailscale Inc & contributors
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by gen.go; DO NOT EDIT.

//go:build !ts_omit_udptransport

package buildfeatures

// HasUDPTransport is whether the binary was built with support for modular feature "UDP transport to peers (if omitted, all peer traffic is relayed over DERP)".
// Specifically, it's whether the binary was NOT built with the "ts_omit_udptransport" build tag.
// It's a const so it can be used for dead code elimination.
const HasUDPTransport = true
