// Copyright (c) Tailscale Inc & AUTHORS
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by gen-featuretags.go; DO NOT EDIT.

//go:build ts_omit_drive

package featuretags

// Drive is whether the binary was built with support for modular feature "Tailscale Drive (file server) support".
// Specifically, it's whether the binary was NOT built with the "ts_omit_drive" build tag.
// It's a const so it can be used for dead code elimination.
const Drive = false
