// Copyright (c) Tailscale Inc & AUTHORS
// SPDX-License-Identifier: BSD-3-Clause

// Package eventbustest provides helper methods for testing events on the
// [eventbus].
//
// # Usage
//
// The test helper presents a set of generic ideas for testing and a
// few specific helpers.
//
// Generally, tests can be run as:
//
//	bus := eventbustest.NewBus(t)
//	tw := eventbustest.NewWatcher(t, bus)
//	somethingThatEmitsSomeEvent()
//	if err := eventbustest.Expect[EventFoo](tw); err != nil {
//	  t.Error(err.Error())
//	}
//
// As shown, [Expect] checks that at least one event of the given type occurs
// in the stream generated by the code under test.
//
// To check for specific properties of an event, use [ExpectFunc], which checks
// that at least one event of the given type occurs in the stream for which the
// given function reports true.
//
// To test for multiple events, use [ExpectEvents], which checks that the stream
// contains the given events in the given order, possibly with other events
// interspersed.
//
// To test the complete contents of the stream, use [ExpectOnlyEvents], which checks
// that the stream contains exactly the given events in the given order, and no
// others.
//
// To test for multiple events like with [ExpectEvents] but needing to inspect
// the events themselves like with [ExpectFunc], use [ExpectEventsFunc].
//
// To test the complete contents of the stream like [ExpectOnlyEvents], but
// needing to inspect the events themselves like with [ExpectFunc], use
// [ExpectOnlyEventsFunc].
//
// See the [usage examples].
//
// [usage examples]: https://github.com/tailscale/tailscale/blob/main/util/eventbus/eventbustest/examples_test.go
package eventbustest
