// Copyright (c) Tailscale Inc & AUTHORS
// SPDX-License-Identifier: BSD-3-Clause

package eventbustest

import (
	"fmt"
	"reflect"
	"testing"
	"time"

	"tailscale.com/util/eventbus"
)

// NewBus constructs an [eventbus.Bus] and sets up cleanup functions for the passed
// test context.
func NewBus(t *testing.T) *eventbus.Bus {
	bus := eventbus.New()
	t.Cleanup(func() {
		bus.Close()
	})
	return bus
}

// NewTestWatcher constructs a [Watcher] that can be used to check the stream of
// events generated by code under test. After construction the caller may use
// [Expect], [ExpectFunc], [ExpectEvents], [ExpectOnlyEvents],
// [ExpectEventsFunc] and [ExpectOnlyEventsFunc] to verify that the desired
// events were captured.
func NewWatcher(t *testing.T, bus *eventbus.Bus) *Watcher {
	tw := &Watcher{
		mon:     bus.Debugger().WatchBus(),
		TimeOut: 5 * time.Second,
		chDone:  make(chan bool, 1),
		events:  make(chan any, 100),
	}
	if deadline, ok := t.Deadline(); ok {
		tw.TimeOut = deadline.Sub(time.Now())
	}
	t.Cleanup(func() {
		tw.done()
	})
	go tw.watch()
	return tw
}

// Watcher monitors and holds events for test expectations.
type Watcher struct {
	mon    *eventbus.Subscriber[eventbus.RoutedEvent]
	events chan any
	chDone chan bool
	// TimeOut defines when the Expect* functions should stop looking for events
	// coming from the Watcher. The value is set by [NewWatcher] and defaults to
	// the deadline passed in by [testing.T]. If looking to verify the absence
	// of an event, the TimeOut can be set to a lower value after creating the
	// Watcher.
	TimeOut time.Duration
}

// Expect is a particular implementation of [ExpectFunc] that tests for the
// existence of an event without caring about the contents of it.
func Expect[T any](tw *Watcher) error {
	return ExpectFunc(tw, func(event T) (bool, error) { return true, nil })
}

// ExpectFunc tests for a particular event but also a particular shape of said event.
// This allows for looking for a single event with a specific value, or a
// particular event in a pile of SomeEvent.
func ExpectFunc[T any](tw *Watcher, test func(event T) (bool, error)) error {
	eventCount := 0
	for {
		select {
		case event := <-tw.events:
			eventCount = eventCount + 1
			if ev, ok := event.(T); ok {
				if ok, err := test(ev); ok {
					return nil
				} else if err != nil {
					return err
				}
			}
		case <-time.After(tw.TimeOut):
			return fmt.Errorf("timed out waiting for event, saw %d events", eventCount)
		}
	}
}

// ExpectEvents tests for a particular set of events in an order but other events
// can happen at the same time. The contents of the events will not be tested,
// only the event type itself.
func ExpectEvents(tw *Watcher, events ...any) error {
	eventCount := 0
	head := 0
	for head < len(events) {
		select {
		case event := <-tw.events:
			eventCount = eventCount + 1
			typeEvent := reflect.TypeOf(event)
			typeHead := reflect.TypeOf(events[head])
			if typeEvent == typeHead {
				head = head + 1
			}
		case <-time.After(tw.TimeOut):
			return fmt.Errorf(
				"timed out waiting for event, saw %d events, %d was expected",
				eventCount, head)
		}
	}
	return nil
}

// ExpectOnlyEvents tests for a particular set of events in an order but other events
// are not allowed to happen at the same time. The contents of the events will not be tested,
// only the event type itself.
func ExpectOnlyEvents(tw *Watcher, events ...any) error {
	eventCount := 0
	head := 0
	for head < len(events) {
		select {
		case event := <-tw.events:
			eventCount = eventCount + 1
			typeEvent := reflect.TypeOf(event)
			typeHead := reflect.TypeOf(events[head])
			if typeEvent != typeHead {
				return fmt.Errorf(
					"expected event type %s, saw %s, at index %d",
					typeHead, typeEvent, head)
			}
			head = head + 1
		case <-time.After(tw.TimeOut):
			return fmt.Errorf(
				"timed out waiting for event, saw %d events, %d was expected",
				eventCount, head)
		}
	}
	return nil
}

// EventFunc is a test helper type that holds an event an a function to test the
// validity of that event. F returns indicates:
//
//	true, nil - Event matches, continue processing
//	false, nil - Event does not match, skip and continue processing
//	*, error - Stop processing, return error
//
// See [ExpectEventsFunc] for example.
type EventFunc struct {
	Event any
	F     func(event any) (bool, error)
}

// ExpectEventsFunc checks for some number of events showing up on the event bus
// in a given order, disregarding any events happening in between.
// If the list of events must match exactly with no extra events,
// use [ExpectOnlyEventsFunc].
func ExpectEventsFunc(tw *Watcher, events ...EventFunc) error {
	eventCount := 0
	head := 0
	for head < len(events) {
		select {
		case event := <-tw.events:
			eventCount = eventCount + 1
			typeEvent := reflect.TypeOf(event)
			typeHead := reflect.TypeOf(events[head].Event)
			if typeEvent == typeHead {
				if ok, err := events[head].F(event); err != nil {
					return err
				} else if ok {
					head = head + 1
				}
			}
		case <-time.After(tw.TimeOut):
			return fmt.Errorf(
				"timed out waiting for event, saw %d events, %d was expected",
				eventCount, head)
		}
	}
	return nil
}

// ExpectOnlyEventsFunc checks for some number of events showing up on the event bus
// in a given order, returning an error if the events does not match the given list
// exactly. Use [ExpectEventsFunc] if other events are allowed.
func ExpectOnlyEventsFunc(tw *Watcher, events ...EventFunc) error {
	eventCount := 0
	head := 0
	for head < len(events) {
		select {
		case event := <-tw.events:
			eventCount = eventCount + 1
			typeEvent := reflect.TypeOf(event)
			typeHead := reflect.TypeOf(events[head].Event)
			if typeEvent != typeHead {
				return fmt.Errorf(
					"expected event type %s, saw %s, at index %d",
					typeHead, typeEvent, head)
			}
			if ok, err := events[head].F(event); err != nil {
				return err
			} else if !ok {
				return fmt.Errorf(
					"expected test ok for type %s, at index %d", typeHead, head)
			}
			head = head + 1
		case <-time.After(tw.TimeOut):
			return fmt.Errorf(
				"timed out waiting for event, saw %d events, %d was expected",
				eventCount, head)
		}
	}
	return nil
}

func (tw *Watcher) watch() {
	for {
		select {
		case event := <-tw.mon.Events():
			tw.events <- event.Event
		case <-tw.chDone:
			tw.mon.Close()
			return
		}
	}
}

// done tells the watcher to stop monitoring for new events.
func (tw *Watcher) done() {
	tw.chDone <- true
}
