// Copyright (c) Tailscale Inc & contributors
// SPDX-License-Identifier: BSD-3-Clause

package vmtest_test

import (
	"encoding/json"
	"fmt"
	"slices"
	"strings"
	"testing"
	"time"

	"tailscale.com/cmd/tailscale/tsdnsjsonv0"
	"tailscale.com/tailcfg"
	"tailscale.com/tstest"
	"tailscale.com/tstest/natlab/vmtest"
	"tailscale.com/tstest/natlab/vnet"
	"tailscale.com/types/dnstype"
)

// The openresolv tests use a routed domain that is answered locally from an
// extra record. That is the cheapest DNS config that still reaches
// GetBaseConfig. It has no default resolvers, which would short-circuit
// compileConfig. It also takes no split-DNS shortcut, because openresolv
// reports SupportsSplitDNS() == false.
const (
	orMagicDNSDomain = "tailnet.test"
	orLocalDomain    = "local.example"
	orLocalName      = "host." + orLocalDomain

	// This address is outside the 100.64.x.y block testcontrol assigns to
	// nodes, so an answer can only have come from the extra record.
	orLocalIP = "100.99.99.99"

	// The signature line openresolv writes at the top of resolv.conf.
	orSignature = "# Generated by resolvconf"

	// Substring of the health warning net/dns reports when GetBaseConfig fails
	// (osConfigurationReadWarnable in net/dns/manager.go).
	orDNSReadHealth = "failed to fetch the DNS configuration"

	// A name that no route covers and that only vnet's default DNS server
	// answers. Resolving it proves the query reached the base config's
	// nameservers instead of being answered by quad-100.
	orUpstreamOnlyName = "dualstack-web.example.com"
	orUpstreamOnlyIP   = "5.0.0.100"

	// Tailscale's own resolver. tailscaled points resolv.conf at it once it has
	// configured DNS.
	orQuad100 = "100.100.100.100"
)

// newOpenresolvEnv brings up a single Ubuntu node running upstream openresolv
// with an existing but empty snippet directory, so the only resolvconf snippet
// will be Tailscale's own.
func newOpenresolvEnv(t *testing.T) (*vmtest.Env, *vmtest.Node) {
	t.Helper()
	env := vmtest.New(t,
		vmtest.ControlDNS(orMagicDNSDomain, &tailcfg.DNSConfig{
			Proxied: true, // MagicDNS, so there's a route and quad-100 is in play
			Domains: []string{orLocalDomain},
			Routes: map[string][]*dnstype.Resolver{
				orLocalDomain: nil, // answer locally, from ExtraRecords
			},
			ExtraRecords: []tailcfg.DNSRecord{
				{Name: orLocalName, Type: "A", Value: orLocalIP},
			},
		}))
	node := env.AddNode("node",
		env.AddNetwork("2.1.1.1", "192.168.1.1/24", vnet.EasyNAT),
		vmtest.OS(vmtest.Ubuntu2404),
		vmtest.WithDNSMode(vmtest.DNSOpenresolv))
	env.Start()

	// Otherwise a pass could come from a different DNS manager.
	env.AssertDNSBackend(node, "openresolv")
	return env, node
}

// TestOpenresolvDNS checks that tailscaled configures DNS on a host where
// Tailscale owns the only resolvconf snippet. Before the fix for
// tailscale/tailscale#20825, such a host got no DNS configuration at all.
func TestOpenresolvDNS(t *testing.T) {
	env, node := newOpenresolvEnv(t)

	// tailscaled must have taken over resolv.conf. Checking for quad-100 rather
	// than the signature line alone matters, because natlab provisions a
	// resolv.conf carrying that same signature.
	assertOpenresolvResolvConf(t, env, node,
		[]string{orSignature, orQuad100},
		[]string{vnet.FakeDNSIPv4().String()})

	assertNoDNSReadWarning(t, env, node)

	// Tailscale's snippet must be registered, and it must be the only one.
	// Otherwise the base-config check below would be running against a host
	// this test did not set up.
	if out, err := env.SSHExec(node, "resolvconf -i"); err != nil {
		t.Errorf("resolvconf -i: %v (%s)", err, strings.TrimSpace(out))
	} else if got := strings.Fields(out); !slices.Equal(got, []string{"tailscale"}) {
		t.Errorf("resolvconf -i = %q, want just \"tailscale\"", strings.TrimSpace(out))
	}

	// Resolving through the OS resolver proves that libc really uses that
	// resolv.conf.
	assertResolves(t, env, node, orLocalName, orLocalIP)

	// Tailscale's snippet is the only one registered, so openresolv has no OS
	// config to report: both the nameservers and the search domains must come
	// back empty. net/dns filters the Tailscale service IPs out of the
	// nameservers anyway (tailscale/tailscale#7816), so the search domains are
	// what this check really rests on.
	base := openresolvBaseConfig(t, env, node)
	if base == nil {
		return // openresolvBaseConfig already reported it
	}
	if len(base.Nameservers) != 0 || len(base.SearchDomains) != 0 {
		t.Errorf("OS base config = %+v, want it empty: Tailscale owns the only "+
			"resolvconf snippet, so openresolv has no OS config to report "+
			"(tailscale/tailscale#20825)", *base)
	}
}

// TestOpenresolvDNSOtherSnippet is the counterweight to TestOpenresolvDNS.
// When another snippet is present, its nameservers must still become quad-100's
// default upstream. Without this test, the fix for #20825 could return early on
// every host and still look correct.
func TestOpenresolvDNSOtherSnippet(t *testing.T) {
	env, node := newOpenresolvEnv(t)

	// Register a second snippet, the way a DHCP client would. It points at
	// vnet's default DNS server, the only thing that answers
	// orUpstreamOnlyName.
	cmd := fmt.Sprintf("printf 'nameserver %s\\n' | resolvconf -a eth0.inet", vnet.FakeDNSIPv4())
	if out, err := env.SSHExec(node, cmd); err != nil {
		t.Fatalf("%s: %v (%s)", cmd, err, strings.TrimSpace(out))
	}

	// tailscaled has no reason to re-read the OS config on its own, so force a
	// full reapply. This is also how the reporter of #20825 reproduced the bug.
	env.SetAcceptDNS(node, false)
	env.SetAcceptDNS(node, true)

	// Both snippets are registered.
	if out, err := env.SSHExec(node, "resolvconf -i"); err != nil {
		t.Errorf("resolvconf -i: %v (%s)", err, strings.TrimSpace(out))
	} else {
		for _, want := range []string{"eth0.inet", "tailscale"} {
			if !slicesContainsField(out, want) {
				t.Errorf("resolvconf -i = %q, want it to list %q", strings.TrimSpace(out), want)
			}
		}
	}

	// Tailscale still owns resolv.conf, so the OS asks quad-100 rather than the
	// other snippet directly. Check that before the lookup at the end of the
	// test. Otherwise a successful lookup might only mean libc went straight to
	// the other snippet's nameserver during the toggle above.
	assertOpenresolvResolvConf(t, env, node,
		[]string{orSignature, orQuad100},
		[]string{vnet.FakeDNSIPv4().String()})

	assertNoDNSReadWarning(t, env, node)

	// tailscaled must read back the other snippet's nameserver and nothing else.
	// An empty config would mean the #20825 early return fired when it should
	// not have, and our own snippet would mean the quad-100 filter did not
	// (tailscale/tailscale#7816).
	if base := openresolvBaseConfig(t, env, node); base != nil {
		if want := vnet.FakeDNSIPv4().String(); !slices.Equal(base.Nameservers, []string{want}) {
			t.Errorf("OS base config nameservers = %q, want just %s", base.Nameservers, want)
		}
	}

	// An answer here can only come from quad-100 forwarding to that base config,
	// since nothing else on the guest answers this name.
	assertResolves(t, env, node, orUpstreamOnlyName, orUpstreamOnlyIP)
}

// assertOpenresolvResolvConf waits for the guest's /etc/resolv.conf to contain
// every string in want and none in notWant.
func assertOpenresolvResolvConf(t *testing.T, env *vmtest.Env, n *vmtest.Node, want, notWant []string) {
	t.Helper()
	const cmd = "cat /etc/resolv.conf"
	var last string
	if err := tstest.WaitFor(60*time.Second, func() error {
		out, err := env.SSHExec(n, cmd)
		last = out
		if err != nil {
			return fmt.Errorf("%s: %v (%s)", cmd, err, strings.TrimSpace(out))
		}
		for _, w := range want {
			if !strings.Contains(out, w) {
				return fmt.Errorf("resolv.conf is missing %q", w)
			}
		}
		for _, w := range notWant {
			if strings.Contains(out, w) {
				return fmt.Errorf("resolv.conf unexpectedly has %q", w)
			}
		}
		return nil
	}); err != nil {
		// The health lines are the fastest way to tell "DNS was never applied"
		// from "DNS was applied but looks wrong".
		t.Fatalf("%v\nwant all of %q and none of %q in resolv.conf:\n%s\nhealth: %q",
			err, want, notWant, last, env.Status(n).Health)
	}
}

// openresolvBaseConfig returns what tailscaled reads back as the node's own OS
// DNS configuration. On failure it calls t.Errorf and returns nil.
//
// "tailscale dns status" fetches it over the local API, which calls straight
// through to openresolvManager.GetBaseConfig, so this is the live result of
// running resolvconf in the guest, not something inferred from its consequences.
func openresolvBaseConfig(t *testing.T, env *vmtest.Env, n *vmtest.Node) *tsdnsjsonv0.SystemConfig {
	t.Helper()
	const cmd = "tailscale dns status --json"
	out, err := env.SSHExec(n, cmd)
	if err != nil {
		t.Errorf("%s: %v (%s)", cmd, err, strings.TrimSpace(out))
		return nil
	}
	var st tsdnsjsonv0.StatusResponse
	if err := json.Unmarshal([]byte(out), &st); err != nil {
		t.Errorf("parsing %s output: %v\n%s", cmd, err, out)
		return nil
	}
	if st.SystemDNSError != "" {
		t.Errorf("tailscaled could not read the OS DNS config: %q", st.SystemDNSError)
		return nil
	}
	if st.SystemDNS == nil {
		t.Errorf("%s reported no OS DNS config:\n%s", cmd, out)
		return nil
	}
	return st.SystemDNS
}

// assertNoDNSReadWarning fails if the node is reporting that it could not read
// the OS DNS configuration.
func assertNoDNSReadWarning(t *testing.T, env *vmtest.Env, n *vmtest.Node) {
	t.Helper()
	for _, h := range env.Status(n).Health {
		if strings.Contains(h, orDNSReadHealth) {
			t.Errorf("node is unhealthy: %q", h)
		}
	}
}

// assertResolves waits for name to resolve to want on the node. It asks for A
// records only, so a name with both an A and a AAAA record cannot come back as
// the wrong address family.
func assertResolves(t *testing.T, env *vmtest.Env, n *vmtest.Node, name, want string) {
	t.Helper()
	cmd := "getent ahostsv4 " + name
	if err := tstest.WaitFor(30*time.Second, func() error {
		out, err := env.SSHExec(n, cmd)
		if err != nil {
			return fmt.Errorf("%s: %v (%s)", cmd, err, strings.TrimSpace(out))
		}
		if !strings.Contains(out, want) {
			return fmt.Errorf("%s = %q, want it to contain %s", cmd, strings.TrimSpace(out), want)
		}
		return nil
	}); err != nil {
		out, _ := env.SSHExec(n, "cat /etc/resolv.conf; resolvconf -i")
		t.Errorf("%v\nresolver state:\n%s", err, out)
	}
}

// slicesContainsField reports whether field appears in out as a complete
// whitespace-separated word, so "tailscale" does not match a longer snippet
// name.
func slicesContainsField(out, field string) bool {
	for _, f := range strings.Fields(out) {
		if f == field {
			return true
		}
	}
	return false
}
